/**
 * 핀플루언서 디렉토리 mock data — 와꾸 미리보기용.
 *
 * 실제 DB의 creators 가 부족할 때 채워서 layout 검증.
 * 실제 user_id 가 아니므로 클릭해도 페이지 진입 안 됨 (slug 클릭은 작동).
 */
import type { Creator } from './creator';

type MockCreator = Omit<Creator, 'created_at' | 'updated_at'> & {
  // 디렉토리 카드에서만 쓰는 추가 필드 (UI 전용)
  accuracy?: number;          // 픽 적중률 (0-100)
  avgYield?: number;          // 평균 수익률
  badge?: string;             // "공식·검증 / 인기" 등
  coverGradient?: string;     // 커버 이미지 대신 그라디언트
};

export const MOCK_CREATORS: MockCreator[] = [
  {
    id: 'mock-1',
    user_id: 'mock-u1',
    slug: 'gangnam-etf',
    display_name: '강남구ETF분석가',
    bio: 'KODEX · TIGER · ACE — 국내 ETF 전 종목 추적. 매주 비교 리포트.',
    avatar_url: '🎯',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #1B64DA 0%, #3182F6 100%)',
    channel_url: null,
    topics: ['ETF', '국내주식·ETF', '시장 인사이트'],
    membership_enabled: true,
    membership_price_won: 9900,
    membership_tier_name: '프리미엄 멤버',
    membership_perks: '주 2회 ETF 비교 리포트\n월 1회 라이브 Q&A\n멤버 채팅방 입장',
    follower_count: 1247,
    member_count: 32,
    post_count: 47,
    is_published: true,
    accuracy: 78,
    badge: '공식·검증',
  },
  {
    id: 'mock-2',
    user_id: 'mock-u2',
    slug: 'macro-curator',
    display_name: '매크로큐레이터',
    bio: '미 연준·금리·환율을 매일 한 줄로. 시장 흐름 놓치지 않게.',
    avatar_url: '🌐',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #7C4DFF 0%, #B383FF 100%)',
    channel_url: null,
    topics: ['시장 인사이트', '해외주식·ETF'],
    membership_enabled: true,
    membership_price_won: 7900,
    membership_tier_name: '월간 구독자',
    membership_perks: '매일 매크로 한입\n주 1회 시장 점검\nFOMC 라이브 해설',
    follower_count: 856,
    member_count: 18,
    post_count: 124,
    is_published: true,
    badge: '데일리 발행',
  },
  {
    id: 'mock-3',
    user_id: 'mock-u3',
    slug: 'buffett-junior',
    display_name: '버핏주니어',
    bio: '가치투자 한 우물 10년. 종목 픽 적중률·수익률 자동 공개.',
    avatar_url: '🦬',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #2E9C5C 0%, #44C781 100%)',
    channel_url: null,
    topics: ['주식', '대가 분석'],
    membership_enabled: true,
    membership_price_won: 19900,
    membership_tier_name: '버크셔 멤버',
    membership_perks: '주간 종목 픽 + 매수 근거\n월간 포트폴리오 공개\n자체 적중률 리포트',
    follower_count: 3210,
    member_count: 95,
    post_count: 86,
    is_published: true,
    accuracy: 80,
    avgYield: 12.4,
    badge: '🔥 인기 TOP 3',
  },
  {
    id: 'mock-4',
    user_id: 'mock-u4',
    slug: 'tax-saver',
    display_name: '세금줄이는법',
    bio: '회계사 12년차. 직장인이 놓치는 절세 포인트를 한입에.',
    avatar_url: '🧾',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #FF9F1C 0%, #FFC36B 100%)',
    channel_url: null,
    topics: ['절세'],
    membership_enabled: true,
    membership_price_won: 4900,
    membership_tier_name: '월간 멤버',
    membership_perks: '연말정산 가이드\n양도소득세 시뮬레이션\n분기별 절세 체크리스트',
    follower_count: 412,
    member_count: 8,
    post_count: 23,
    is_published: true,
    badge: '회계사 인증',
  },
  {
    id: 'mock-5',
    user_id: 'mock-u5',
    slug: 'realestate-bite',
    display_name: '내집한입',
    bio: '서울·수도권 분양·청약·재건축까지. 데이터로 보는 부동산.',
    avatar_url: '🏠',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #E94986 0%, #FF8FB7 100%)',
    channel_url: null,
    topics: ['부동산'],
    membership_enabled: true,
    membership_price_won: 14900,
    membership_tier_name: '내집 멤버',
    membership_perks: '주간 청약 단지 분석\n월간 시세 리포트\n전세·매매 타이밍 알림',
    follower_count: 980,
    member_count: 45,
    post_count: 58,
    is_published: true,
  },
  {
    id: 'mock-6',
    user_id: 'mock-u6',
    slug: 'coin-strategy',
    display_name: '코인한입',
    bio: '비트코인 · 이더리움 · 알트까지. 매크로와 연결한 코인 전략.',
    avatar_url: '🪙',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #FFB400 0%, #FFD16B 100%)',
    channel_url: null,
    topics: ['코인'],
    membership_enabled: true,
    membership_price_won: 12900,
    membership_tier_name: '온체인 멤버',
    membership_perks: '주간 온체인 데이터\n알트 픽 + 손절가\nETF 자금 흐름 분석',
    follower_count: 1820,
    member_count: 67,
    post_count: 91,
    is_published: true,
    badge: '🔥 인기',
  },
  {
    id: 'mock-7',
    user_id: 'mock-u7',
    slug: 'retire-bite',
    display_name: '은퇴한입',
    bio: '40대부터 시작하는 은퇴 설계. 연금·ISA·IRP 한 번에.',
    avatar_url: '🌅',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #4A90E2 0%, #7AB1FF 100%)',
    channel_url: null,
    topics: ['은퇴 설계', '월급쟁이 재테크'],
    membership_enabled: true,
    membership_price_won: 5900,
    membership_tier_name: '월간 멤버',
    membership_perks: '나이별 설계 시뮬레이션\n월간 점검 리포트\n질문 답변 우선',
    follower_count: 234,
    member_count: 5,
    post_count: 18,
    is_published: true,
  },
  {
    id: 'mock-8',
    user_id: 'mock-u8',
    slug: 'dividend-farmer',
    display_name: '배당농부',
    bio: '월배당·분기배당으로 현금흐름 만들기. 평균 배당률 5.2%.',
    avatar_url: '🌾',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #00A86B 0%, #44C781 100%)',
    channel_url: null,
    topics: ['ETF', '월급쟁이 재테크'],
    membership_enabled: true,
    membership_price_won: 9900,
    membership_tier_name: '농부 멤버',
    membership_perks: '월간 배당 캘린더\n신규 배당주 발굴\nKR·US 환율 시그널',
    follower_count: 1430,
    member_count: 78,
    post_count: 62,
    is_published: true,
    avgYield: 5.2,
    badge: '월배당 전문',
  },
  {
    id: 'mock-9',
    user_id: 'mock-u9',
    slug: 'wallst-bite',
    display_name: '월스트리트한입',
    bio: 'NY 본사 펀드 출신. 미국 증시 인사이트를 한국말로.',
    avatar_url: '🗽',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #1A237E 0%, #3F51B5 100%)',
    channel_url: null,
    topics: ['해외주식·ETF', '대가 분석'],
    membership_enabled: true,
    membership_price_won: 14900,
    membership_tier_name: '월스트리트 멤버',
    membership_perks: '주간 미 증시 리포트\nETF 자금 흐름\n13F 공시 해설',
    follower_count: 2100,
    member_count: 42,
    post_count: 73,
    is_published: true,
    badge: '전문가 인증',
  },
  {
    id: 'mock-10',
    user_id: 'mock-u10',
    slug: 'short-trader',
    display_name: '단타다이어리',
    bio: '하루 한 종목, 한 줄로 정리. 신생 채널입니다.',
    avatar_url: '⚡',
    cover_url: null,
    coverGradient: 'linear-gradient(135deg, #555 0%, #888 100%)',
    channel_url: null,
    topics: ['주식'],
    membership_enabled: false,
    membership_price_won: null,
    membership_tier_name: '멤버',
    membership_perks: null,
    follower_count: 124,
    member_count: 0,
    post_count: 8,
    is_published: true,
    badge: '🆕 신규',
  },
];

/** mock 을 Creator 타입으로 캐스팅 (날짜 추가) */
export function getMockCreators(): Creator[] {
  const now = new Date().toISOString();
  return MOCK_CREATORS.map(m => ({
    ...m,
    created_at: now,
    updated_at: now,
  }));
}

export type MockCreatorWithStats = MockCreator & { created_at: string; updated_at: string };
