export const sampleQuestions = [
  {
    id: 1,
    cat: '재테크입문',
    topic: '저축·목돈',
    author: '신림동의현인',
    time: '3시간 전',
    em: '🐰',
    lv: 2,
    title: '월급 300만원인데 저축은 얼마나 해야 하나요?',
    body: '사회초년생이고 세후 월급은 300만원 정도입니다. 월세와 고정지출을 빼면 140~150만원이 남는데, 적금·비상금·투자 비율을 어떻게 나눠야 할지 모르겠어요.',
    ans: 12,
    adopted: true,
    slug: 'monthly-300',
    createdAt: '2026-05-08T23:20:00+09:00',
    likeCount: 34,
    viewCount: 1287,
  },
  {
    id: 2,
    cat: '국내주식·ETF',
    topic: 'ETF',
    author: '소현버핏',
    time: '6시간 전',
    em: '🦊',
    lv: 1,
    title: 'S&P500 ETF 지금 들어가도 늦지 않나요? 고점 아닌가요?',
    body: 'VOO나 SPY를 매달 사려고 하는데 최근 지수가 많이 오른 것 같아서 시작 타이밍이 고민됩니다. 한 번에 넣기보다 분할 매수가 맞을까요?',
    ans: 28,
    adopted: true,
    slug: 'sp500-etf',
    createdAt: '2026-05-08T20:05:00+09:00',
    likeCount: 71,
    viewCount: 3420,
    tags: ['S&P500', '미국 ETF', '분할매수'],
  },
  {
    id: 3,
    cat: '절세',
    topic: 'ISA·연금저축',
    author: '여의도세액공제',
    time: '1일 전',
    em: '🐻',
    lv: 1,
    title: 'ISA 계좌랑 연금저축 중에 뭐 먼저 채워야 하나요?',
    body: '월 80만원 정도 투자 여력이 있습니다. ISA, 연금저축, IRP를 다 하라는 말은 많은데 순서를 어떻게 잡아야 할지 헷갈립니다.',
    ans: 9,
    adopted: true,
    slug: 'isa-vs-pension',
    createdAt: '2026-05-08T19:42:00+09:00',
    likeCount: 45,
    viewCount: 2186,
  },
  {
    id: 4,
    cat: '보험',
    topic: '실손보험',
    author: '잠실보장분석가',
    time: '1일 전',
    em: '🦋',
    lv: 2,
    title: '실손보험 꼭 있어야 하나요? 건강한 20대인데 없어도 될까요?',
    body: '20대 후반이고 회사 단체보험이 있습니다. 개인 실손보험을 새로 들어야 하는지, 단체보험만 믿어도 되는지 판단 기준이 궁금합니다.',
    ans: 15,
    adopted: true,
    slug: 'silson-insurance',
    createdAt: '2026-05-08T11:10:00+09:00',
    likeCount: 52,
    viewCount: 2661,
  },
  {
    id: 5,
    cat: '대출·부채',
    topic: '상환전략',
    author: '마포상환왕',
    time: '2일 전',
    em: '🐯',
    lv: 1,
    title: '학자금대출 먼저 갚을까요, 비상금부터 모을까요?',
    body: '학자금대출이 900만원 정도 남았고 금리는 1%대입니다. 월 70만원 정도 여유가 있는데 대출 상환과 비상금 마련 중 무엇을 먼저 해야 할까요?',
    ans: 11,
    adopted: true,
    slug: 'student-loan-emergency-fund',
    createdAt: '2026-05-07T22:18:00+09:00',
    likeCount: 39,
    viewCount: 1944,
  },
  {
    id: 6,
    cat: '재테크입문',
    topic: '청년통장',
    author: '봉천동복리주의자',
    time: '3일 전',
    em: '🐼',
    lv: 0,
    title: '청년도약계좌 넣으면서 투자도 같이 해도 될까요?',
    body: '청년도약계좌에 매달 50만원을 넣고 있습니다. 남는 돈이 40만원 정도 있는데 적금을 더 하는 게 나은지, ETF를 조금씩 사도 되는지 궁금합니다.',
    ans: 8,
    adopted: false,
    slug: 'youth-account-investing',
    createdAt: '2026-05-06T18:34:00+09:00',
    likeCount: 26,
    viewCount: 1210,
  },
  {
    id: 7,
    cat: '국내주식·ETF',
    topic: '배당',
    author: '판교배당수집가',
    time: '5일 전',
    em: '🦁',
    lv: 3,
    title: '배당 ETF는 초보자가 시작하기 괜찮은가요?',
    body: '월배당 ETF가 좋아 보여서 관심이 생겼습니다. 배당금이 들어오면 심리적으로 버티기 좋을 것 같은데, 장기 수익률이나 세금까지 보면 어떤 점을 조심해야 하나요?',
    ans: 17,
    adopted: true,
    slug: 'dividend-etf-beginner',
    createdAt: '2026-05-04T15:27:00+09:00',
    likeCount: 63,
    viewCount: 3018,
    tags: ['배당 ETF', '월배당', '세금'],
  },
  {
    id: 8,
    cat: '절세',
    topic: '연말정산',
    author: '을지로가계부고수',
    time: '7일 전',
    em: '🐨',
    lv: 2,
    title: '월세 세액공제 받으려면 지금부터 뭘 챙겨야 하나요?',
    body: '올해 처음 자취를 시작했습니다. 월세 세액공제를 받을 수 있다고 들었는데 계약서, 이체내역, 전입신고 중 어떤 걸 미리 챙겨야 하나요?',
    ans: 6,
    adopted: true,
    slug: 'monthly-rent-tax-credit',
    createdAt: '2026-05-02T21:40:00+09:00',
    likeCount: 31,
    viewCount: 1502,
  },
  {
    id: 8,
    cat: '해외주식·ETF',
    topic: 'ETF',
    author: '서래마을주니어',
    time: '1일 전',
    em: '🐼',
    lv: 1,
    title: 'VOO 살까 TIGER 미국S&P500 살까요?',
    body: '환전 수수료 + 양도세 22% 생각하면 국내 상장이 나을 것 같은데, 운용보수 차이는 어느 정도까지 의미가 있을지 모르겠어요. 5천만원 단위로 장기 적립할 예정입니다.',
    ans: 18,
    adopted: true,
    slug: 'voo-vs-tiger-sp500',
    createdAt: '2026-05-12T08:30:00+09:00',
    likeCount: 58,
    viewCount: 2845,
    tags: ['VOO', 'TIGER 미국S&P500', '국내상장', '양도세'],
  },
  {
    id: 9,
    cat: '국내주식·ETF',
    topic: '월배당',
    author: '동탄러닝맨',
    time: '2일 전',
    em: '🦋',
    lv: 2,
    title: 'JEPI나 SCHD 월배당 ETF, 환차익이 더 손해 아닌가요?',
    body: '월배당 받는다고 좋아했는데 배당받을 때마다 15% 원천징수 + 환율 떨어지면 원화 가치가 더 줄어드는 것 같아요. 국내 월배당 ETF가 더 안정적일까요?',
    ans: 14,
    adopted: false,
    slug: 'jepi-schd-vs-kr-monthly',
    createdAt: '2026-05-11T19:15:00+09:00',
    likeCount: 47,
    viewCount: 2103,
    tags: ['JEPI', 'SCHD', '월배당', '환차익'],
  },
  {
    id: 10,
    cat: '재테크입문',
    topic: '자산배분',
    author: '판교주니어',
    time: '3일 전',
    em: '🐸',
    lv: 1,
    title: '레이 달리오 올웨더 포트폴리오, 한국에서도 그대로 적용해도 되나요?',
    body: '책 보고 올웨더 따라해보고 싶은데 미국 ETF로 다 사면 환율 변동이 너무 클 것 같아요. 국내 ETF로 비슷하게 구성하면 효과가 떨어질까요?',
    ans: 22,
    adopted: true,
    slug: 'all-weather-kr',
    createdAt: '2026-05-10T11:45:00+09:00',
    likeCount: 73,
    viewCount: 3567,
    tags: ['올웨더', '레이 달리오', '자산배분'],
  },
  {
    id: 11,
    cat: '재테크입문',
    topic: 'ISA',
    author: '의정부예금왕',
    time: '5일 전',
    em: '🦊',
    lv: 1,
    title: 'ISA 만기 3년 다 됐는데 연금저축으로 이체할까 그냥 해지할까요?',
    body: '청약저축 빼고 처음으로 ISA 만기를 맞이합니다. 누적 수익이 200만원 정도 났는데 어떻게 해야 세제 혜택을 가장 많이 받을지 모르겠어요.',
    ans: 9,
    adopted: true,
    slug: 'isa-maturity-rollover',
    createdAt: '2026-05-08T14:22:00+09:00',
    likeCount: 28,
    viewCount: 1287,
    tags: ['ISA', '연금저축', '만기'],
  },
  {
    id: 12,
    cat: '국내주식·ETF',
    topic: '반도체',
    author: '시그니엘분양받고싶다',
    time: '6일 전',
    em: '🐰',
    lv: 2,
    title: 'TIGER 반도체와 SOXX 둘 다 가지고 있는데 중복 아닐까요?',
    body: '국내 반도체 ETF와 미국 반도체 ETF를 같이 사면 분산 효과가 있을지, 아니면 둘 다 결국 삼성·SK하이닉스·엔비디아 의존도가 커서 중복일지 헷갈립니다.',
    ans: 11,
    adopted: false,
    slug: 'kr-us-semis-overlap',
    createdAt: '2026-05-07T10:00:00+09:00',
    likeCount: 39,
    viewCount: 1894,
    tags: ['반도체', 'TIGER', 'SOXX', '중복'],
  },
  {
    id: 13,
    cat: '해외주식·ETF',
    topic: '커버드콜',
    author: '신논현피라미',
    time: '1주 전',
    em: '🐯',
    lv: 1,
    title: '커버드콜 ETF는 왜 다들 위험하다고 하나요? 월배당이 매력적인데',
    body: 'TIGER 미국나스닥100커버드콜 같은 거 월 1% 이상씩 분배해줘서 좋아 보이는데 유튜브에선 다들 비추하더라고요. 어떤 위험이 있는 건가요?',
    ans: 15,
    adopted: true,
    slug: 'covered-call-risk',
    createdAt: '2026-05-06T22:10:00+09:00',
    likeCount: 51,
    viewCount: 2456,
    tags: ['커버드콜', '월배당', '위험'],
  },
  {
    id: 14,
    cat: '재테크입문',
    topic: '리밸런싱',
    author: '광교호숫가',
    time: '1주 전',
    em: '🦁',
    lv: 2,
    title: '리밸런싱은 얼마나 자주, 어떻게 해야 하나요?',
    body: '주식 60% 채권 40% 비중을 정해놨는데 주식이 많이 올라서 70:30 정도 됐어요. 지금 팔아야 할까요? 아니면 1년에 한 번씩만 하면 될까요?',
    ans: 17,
    adopted: true,
    slug: 'rebalancing-frequency',
    createdAt: '2026-05-04T16:30:00+09:00',
    likeCount: 62,
    viewCount: 2837,
    tags: ['리밸런싱', '자산배분', '주식·채권'],
  },
  {
    id: 15,
    cat: '재테크입문',
    topic: '월금',
    author: '비온뒤맑음',
    time: '2주 전',
    em: '🐮',
    lv: 1,
    title: '연금저축 vs IRP, 둘 다 들어야 할까요?',
    body: '직장인이고 세액공제 700만원 한도까지 채우고 싶은데 연금저축 400 + IRP 300 이렇게 하는 게 맞나요? 운용 차이도 궁금합니다.',
    ans: 12,
    adopted: false,
    slug: 'pension-irp-combo',
    createdAt: '2026-04-28T09:50:00+09:00',
    likeCount: 36,
    viewCount: 1623,
    tags: ['연금저축', 'IRP', '세액공제'],
  },
];

export type Question = {
  id: number;
  cat: string;
  topic: string;
  author: string;
  time: string;
  em: string;
  lv: number;
  title: string;
  body: string;
  ans: number;
  adopted: boolean;
  slug: string;
  dbId?: string;
  createdAt?: string;
  likeCount?: number;
  viewCount?: number;
  tags?: string[];
};

export type SampleAnswer = {
  id: string;
  body: string;
  author: string;
  createdAt: string;
  likeCount: number;
  adopted?: boolean;
};

export const sampleAnswersBySlug: Record<string, SampleAnswer[]> = {
  'monthly-300': [
    {
      id: 'monthly-300-a1',
      author: '을지로가계부고수',
      createdAt: '2026-05-09T00:04:00+09:00',
      likeCount: 42,
      adopted: true,
      body: '월 300만원이면 먼저 “남는 돈을 저축”보다 “월급일에 자동으로 빠져나가게 하는 구조”가 중요해요. 고정지출 후 150만원이 남는다면 비상금 40만원, 단기목표 적금 50만원, 장기투자 40만원, 자유예산 20만원처럼 처음에는 과하게 빡빡하지 않게 나누는 걸 추천합니다. 비상금이 3개월치 생활비까지 쌓이면 그때 장기투자 비중을 조금 올려도 됩니다.',
    },
    {
      id: 'monthly-300-a2',
      author: '마포현금흐름',
      createdAt: '2026-05-09T01:16:00+09:00',
      likeCount: 19,
      body: '핵심은 비율보다 지속 가능성입니다. 처음부터 100만원 이상 묶어버리면 2~3개월 뒤 카드값 때문에 깨는 경우가 많아요. 저는 3개월만 50% 저축률을 테스트해보고, 생활이 무너지지 않으면 55~60%로 올리는 방식을 권해요.',
    },
    {
      id: 'monthly-300-a3',
      author: '한강리밸런싱',
      createdAt: '2026-05-09T02:21:00+09:00',
      likeCount: 13,
      body: '투자는 비상금과 단기 목표를 분리한 뒤에 시작하는 게 좋아요. 결혼, 이사, 여행처럼 1~3년 안에 쓸 돈은 예금·적금 쪽에 두고, 5년 이상 안 쓸 돈만 ETF 같은 변동성 자산으로 보내면 흔들릴 때 버티기 쉽습니다.',
    },
  ],
  'sp500-etf': [
    {
      id: 'sp500-etf-a1',
      author: '판교장기투자자',
      createdAt: '2026-05-08T21:02:00+09:00',
      likeCount: 58,
      adopted: true,
      body: '고점이 걱정될수록 정답은 “맞히기”보다 “나눠 들어가기”에 가깝습니다. 매수 자금이 1,000만원이라면 6~12개월로 나누고, 이후에는 월급에서 정해진 금액을 자동매수하는 식이 좋아요. S&P500은 단기 고점 여부보다 투자 기간, 환율, 중간에 팔지 않을 구조가 더 중요합니다.',
    },
    {
      id: 'sp500-etf-a2',
      author: '광화문ETF노트',
      createdAt: '2026-05-08T22:25:00+09:00',
      likeCount: 33,
      body: 'VOO, IVV, SPY는 큰 방향은 비슷하지만 수수료와 거래 편의성이 조금씩 달라요. 초보라면 상품 비교보다 먼저 “원화 환전 시점”, “월 적립 금액”, “하락 시 추가매수 규칙”을 정해두는 게 실수 방지에 더 도움이 됩니다.',
    },
    {
      id: 'sp500-etf-a3',
      author: '서초분산투자',
      createdAt: '2026-05-09T00:47:00+09:00',
      likeCount: 21,
      body: '한 번에 전액 매수하면 수익률보다 감정 관리가 어려울 수 있어요. 특히 첫 투자라면 계좌가 -10%만 되어도 생각보다 크게 흔들립니다. 적립식으로 시작해서 내 변동성 체력을 확인하는 게 장기적으로 더 안전합니다.',
    },
  ],
  'isa-vs-pension': [
    {
      id: 'isa-vs-pension-a1',
      author: '여의도절세계산기',
      createdAt: '2026-05-08T20:10:00+09:00',
      likeCount: 31,
      adopted: true,
      body: '돈을 오래 묶어도 되는지부터 나누면 쉬워요. 3~5년 안에 쓸 가능성이 있으면 ISA를 먼저 채우고, 노후자금처럼 오래 묶어도 되는 돈이면 연금저축을 우선 검토하세요. 연금저축은 세액공제 장점이 크지만 중도 인출 제약과 과세 구조를 같이 봐야 합니다.',
    },
    {
      id: 'isa-vs-pension-a2',
      author: '종로연금메모',
      createdAt: '2026-05-08T22:33:00+09:00',
      likeCount: 16,
      body: '월 80만원이면 ISA 50만원, 연금저축 30만원처럼 시작해도 충분합니다. 연말에 소득과 세액공제 한도를 보고 연금저축을 추가 납입하는 방식이 부담이 적어요.',
    },
  ],
  'silson-insurance': [
    {
      id: 'silson-insurance-a1',
      author: '잠실보장리뷰',
      createdAt: '2026-05-08T12:06:00+09:00',
      likeCount: 37,
      adopted: true,
      body: '20대라도 실손은 “지금 건강하냐”보다 “나중에 가입이 어려워질 수 있냐”를 봐야 합니다. 단체보험은 퇴사나 이직 시 끊길 수 있어서 개인 실손을 최소 보장으로 가져가는 선택이 흔해요. 다만 중복 보상 구조는 꼭 확인하세요.',
    },
    {
      id: 'silson-insurance-a2',
      author: '강남보험정리',
      createdAt: '2026-05-08T13:48:00+09:00',
      likeCount: 22,
      body: '보험료가 부담된다면 종합보험을 크게 들기보다 실손, 가족력에 맞춘 최소 보장, 비상금 순서로 생각해보세요. “해지하면 손해”라는 말보다 지금 내 현금흐름에서 감당 가능한지가 더 중요합니다.',
    },
  ],
  'student-loan-emergency-fund': [
    {
      id: 'student-loan-emergency-fund-a1',
      author: '마포상환플랜',
      createdAt: '2026-05-07T23:11:00+09:00',
      likeCount: 28,
      adopted: true,
      body: '금리가 1%대라면 전액 조기상환보다 비상금 확보가 먼저입니다. 최소 300만원, 가능하면 3개월 생활비까지 만든 뒤 남는 돈으로 일부 상환하세요. 급한 일이 생겼을 때 다시 고금리 대출을 쓰는 상황을 막는 게 더 큰 이득입니다.',
    },
    {
      id: 'student-loan-emergency-fund-a2',
      author: '성수현금관리',
      createdAt: '2026-05-08T08:32:00+09:00',
      likeCount: 11,
      body: '월 70만원이면 비상금 50만원, 대출상환 20만원으로 시작해보세요. 비상금 목표액을 채운 뒤에는 상환액을 50만원 이상으로 올리면 심리적으로도 속도가 붙습니다.',
    },
  ],
  'youth-account-investing': [
    {
      id: 'youth-account-investing-a1',
      author: '구로월급분배',
      createdAt: '2026-05-06T20:12:00+09:00',
      likeCount: 18,
      body: '청년도약계좌를 이미 꾸준히 넣고 있다면 남는 돈 전부를 추가 적금으로 묶을 필요는 없습니다. 다만 투자 경험이 적다면 월 10~20만원 정도로 시작해서 계좌 변동에 익숙해지는 과정이 먼저예요.',
    },
    {
      id: 'youth-account-investing-a2',
      author: '신촌복리노트',
      createdAt: '2026-05-07T09:25:00+09:00',
      likeCount: 9,
      body: '목돈 사용 시점이 2년 이내라면 적금 비중을 높이고, 5년 이상 안 쓸 돈이면 ETF 비중을 조금씩 가져가도 됩니다. 청년도약계좌는 중도 해지 리스크가 있으니 생활비 쿠션은 따로 둬야 해요.',
    },
  ],
  'dividend-etf-beginner': [
    {
      id: 'dividend-etf-beginner-a1',
      author: '판교배당노트',
      createdAt: '2026-05-04T17:03:00+09:00',
      likeCount: 41,
      adopted: true,
      body: '배당 ETF는 현금흐름을 체감하기 좋아서 초보자에게 심리적 장점이 있습니다. 다만 배당이 높다고 무조건 좋은 건 아니고, 총수익률, 분배금 재투자, 세금, 환율을 같이 봐야 해요. 생활비 목적이 아니라면 성장형 ETF와 섞는 편이 균형적입니다.',
    },
    {
      id: 'dividend-etf-beginner-a2',
      author: '합정월배당',
      createdAt: '2026-05-05T10:44:00+09:00',
      likeCount: 17,
      body: '월배당은 “매달 돈이 들어온다”는 장점 때문에 과대평가되기 쉬워요. 분배금이 내 원금 일부를 돌려주는 구조인지, 커버드콜 비중이 큰지, 장기 상승 여력이 제한되는지 확인해야 합니다.',
    },
  ],
  'monthly-rent-tax-credit': [
    {
      id: 'monthly-rent-tax-credit-a1',
      author: '을지로연말정산',
      createdAt: '2026-05-02T22:30:00+09:00',
      likeCount: 24,
      adopted: true,
      body: '월세 세액공제는 전입신고, 임대차계약서, 월세 이체내역이 핵심입니다. 현금으로 주기보다 본인 명의 계좌에서 집주인 계좌로 매달 이체하고, 메모에 월세라고 남겨두면 연말정산 때 훨씬 편합니다.',
    },
    {
      id: 'monthly-rent-tax-credit-a2',
      author: '충무로절세정리',
      createdAt: '2026-05-03T08:18:00+09:00',
      likeCount: 12,
      body: '소득요건과 주택요건도 같이 봐야 합니다. 지금 당장 공제 대상인지 확실하지 않아도 계약서와 이체내역은 미리 챙겨두세요. 나중에 조건이 맞는데 자료가 없어서 놓치는 경우가 많습니다.',
    },
  ],
  'voo-vs-tiger-sp500': [
    {
      id: 'voo-vs-tiger-sp500-a1',
      author: '강남세무사보조',
      createdAt: '2026-05-12T11:20:00+09:00',
      likeCount: 67,
      adopted: true,
      body: '결론부터 — 5천만원 단위 장기라면 TIGER 미국S&P500이 거의 항상 유리합니다. VOO 운용보수 0.03%, TIGER 0.07%로 차이는 연 4bp(0.04%)에 불과한데, 환전 수수료(0.5% 안팎)와 양도세 22%(250만원 공제 후)를 합치면 국내 상장이 1년 안에 비용을 만회합니다. 단 ISA·연금저축 한도를 다 채운 다음에 추가로 넣는 5천만원이라면 미국 직상장도 고려할 만합니다.',
    },
    {
      id: 'voo-vs-tiger-sp500-a2',
      author: '한남동시드머니',
      createdAt: '2026-05-12T15:40:00+09:00',
      likeCount: 31,
      body: '운용보수 0.04% 차이는 1억원 기준 연 4만원입니다. 환전 수수료·세금 차이가 훨씬 크기 때문에 거의 모든 시나리오에서 국내 상장이 유리합니다. 단 미국 직상장은 양도세 분리과세(타 소득과 합산 안 됨)라서 다른 소득이 많은 분이면 그 점은 장점.',
    },
  ],
  'all-weather-kr': [
    {
      id: 'all-weather-kr-a1',
      author: '판교자산배분',
      createdAt: '2026-05-10T13:00:00+09:00',
      likeCount: 89,
      adopted: true,
      body: '달리오 본인이 "올웨더는 비중이 중요하지 정확한 ETF는 부차적"이라고 말했어요. 한국 상장 ETF로 비슷하게 구성 가능합니다 — TIGER 미국S&P500 30% / KODEX 미국채울트라30년선물(H) 40% / TIGER 미국채10년선물(H) 15% / KODEX 골드선물(H) 7.5% / KODEX WTI원유선물(H) 7.5%. ETF한입 대가 페이지에 이 매핑이 이미 정리돼 있습니다.',
    },
    {
      id: 'all-weather-kr-a2',
      author: '서래마을매크로',
      createdAt: '2026-05-10T18:33:00+09:00',
      likeCount: 26,
      body: '단 한 가지 — 국내 선물 ETF는 롤오버 비용이 있어 장기 보유 시 추적오차가 누적될 수 있습니다. 미국 직상장 TLT/IEF가 정확도는 더 높지만 환율 노출이 크니 트레이드오프예요.',
    },
  ],
  'covered-call-risk': [
    {
      id: 'covered-call-risk-a1',
      author: '대치동옵션',
      createdAt: '2026-05-07T08:50:00+09:00',
      likeCount: 44,
      adopted: true,
      body: '커버드콜은 "상승 일부를 포기하고 매월 프리미엄을 받는" 전략입니다. 박스권·하락장에선 강하지만 강세장에선 기초자산보다 한참 뒤처져요. 2020~2023년 나스닥 100이 +90% 갈 때 QYLD는 +30%대였습니다. 분배율이 높아 보여도 결국 기초자산 성과를 깎아 분배로 돌려주는 구조라 NAV가 우하향하는 ETF가 많습니다.',
    },
    {
      id: 'covered-call-risk-a2',
      author: '신논현시그마',
      createdAt: '2026-05-07T20:15:00+09:00',
      likeCount: 18,
      body: '월 1% 분배라고 연 12%가 아닙니다. 기초가 하락하면 NAV도 같이 떨어지고, 분배금에 15.4% 배당소득세까지 부담합니다. 은퇴자처럼 현금흐름이 핵심인 분에게는 의미가 있지만, 자산 증식 목적이면 다른 전략이 낫습니다.',
    },
  ],
  'rebalancing-frequency': [
    {
      id: 'rebalancing-frequency-a1',
      author: '광교포트폴리오',
      createdAt: '2026-05-04T18:00:00+09:00',
      likeCount: 53,
      adopted: true,
      body: '학계 연구 결과로는 1년에 1회 또는 "목표 비중에서 5%p 이상 벗어났을 때"가 가장 효율적입니다. 60:40이 70:30 됐다면 5%p 차이라 리밸런싱 시점이에요. 단 ISA처럼 매도 시 비과세 한도가 있는 계좌가 아니면 매도세금이 발생하니, 새 자금 추가 시 비중 작은 쪽에 더 넣는 "자연 리밸런싱"이 가장 효율적입니다.',
    },
  ],
};

export function getSampleAnswers(slug: string) {
  return sampleAnswersBySlug[slug] || [];
}

export const LEVELS = [
  { l: 'Lv.0', color: '#8B95A1' },
  { l: 'Lv.1', color: '#00C73C' },
  { l: 'Lv.2', color: '#3182F6' },
  { l: 'Lv.3', color: '#F59E0B' },
];

export const EMOJI = ['🐯','🐰','🦊','🐻','🦋','🐸','🐼','🦁','🐨','🐮','🐷','🐙'];
