-- ============================================================
-- 마이그레이션: 스파링 댓글·투표 시스템 v1
-- 실행 위치: Supabase 대시보드 > SQL Editor
-- 기준 카테고리: docs/categories.md 6개 SSOT
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.sparrings (
  id             uuid default gen_random_uuid() primary key,
  round_number   bigint generated by default as identity unique,
  category       text not null check (category in ('재테크입문', '국내주식·ETF', '해외주식·ETF', '절세', '보험', '대출·부채')),
  title          text not null,
  body           text not null,
  slug           text not null unique,
  side_a_label   text not null,
  side_b_label   text not null,
  deadline_at    timestamptz not null,
  status         text not null default 'active' check (status in ('active', 'closed')),
  created_at     timestamptz not null default now(),
  deleted_at     timestamptz
);

create table if not exists public.sparring_votes (
  sparring_id uuid not null references public.sparrings(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  side        text not null check (side in ('a', 'b')),
  voted_at    timestamptz not null default now(),
  unique (sparring_id, user_id)
);

create table if not exists public.sparring_comments (
  id          uuid default gen_random_uuid() primary key,
  sparring_id uuid not null references public.sparrings(id) on delete cascade,
  user_id     uuid references auth.users(id) on delete set null,
  side        text not null check (side in ('a', 'b')),
  body        text not null check (char_length(trim(body)) between 1 and 1200),
  created_at  timestamptz not null default now(),
  deleted_at  timestamptz
);

create index if not exists sparrings_status_deadline_idx
  on public.sparrings (status, deadline_at)
  where deleted_at is null;

create index if not exists sparrings_category_idx
  on public.sparrings (category)
  where deleted_at is null;

create index if not exists sparring_votes_sparring_idx
  on public.sparring_votes (sparring_id, side);

create index if not exists sparring_comments_sparring_idx
  on public.sparring_comments (sparring_id, side, created_at)
  where deleted_at is null;

alter table public.sparrings enable row level security;
alter table public.sparring_votes enable row level security;
alter table public.sparring_comments enable row level security;

create policy "sparrings: 누구나 읽기"
  on public.sparrings for select
  using (deleted_at is null);

create policy "sparring_votes: 누구나 읽기"
  on public.sparring_votes for select
  using (true);

create policy "sparring_votes: 로그인 insert"
  on public.sparring_votes for insert
  with check (auth.uid() = user_id);

create policy "sparring_votes: 본인 update"
  on public.sparring_votes for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "sparring_comments: 누구나 읽기"
  on public.sparring_comments for select
  using (deleted_at is null);

create policy "sparring_comments: 로그인 insert"
  on public.sparring_comments for insert
  with check (auth.uid() = user_id);

create policy "sparring_comments: 본인 soft delete"
  on public.sparring_comments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

insert into public.sparrings (
  round_number,
  category,
  title,
  body,
  slug,
  side_a_label,
  side_b_label,
  deadline_at,
  status
) values (
  1,
  '해외주식·ETF',
  'S&P500 ETF, 지금 들어가도 될까요?',
  'VOO나 SPY를 매달 사려는데 최근 지수가 많이 오른 것 같아 시작 타이밍이 고민돼요. 지금 분할 매수를 시작하는 쪽과 현금을 더 들고 기다리는 쪽, 어느 판단이 더 나을까요?',
  'sp500-etf-entry',
  '분할 매수 시작',
  '현금 유지',
  '2026-05-12 23:59:59+09',
  'active'
) on conflict (slug) do update set
  category = excluded.category,
  title = excluded.title,
  body = excluded.body,
  side_a_label = excluded.side_a_label,
  side_b_label = excluded.side_b_label,
  deadline_at = excluded.deadline_at,
  status = excluded.status,
  deleted_at = null;
